# Generated by Django 4.1.4 on 2022-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0004_card_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
