# Generated by Django 4.1.4 on 2022-12-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0005_card_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('titleImage', models.ImageField(upload_to='uploads/')),
                ('thumbnailImage', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
                ('VIDEOS', models.CharField(choices=[('Music Videos', 'Musicvideos'), ('Web Series', 'Webseries'), ('Movies', 'Movies'), ('Trailers', 'Trailers'), ('Kids', 'Kids'), ('Devotional', 'Devotional')], default='Music Videos', max_length=12)),
                ('trailer', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='imageupload',
        ),
    ]
