# Generated by Django 4.1.4 on 2022-12-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0006_videosdetails_delete_card_delete_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosdetails',
            name='trailer',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Trailer'),
        ),
        migrations.AlterField(
            model_name='videosdetails',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video'),
        ),
    ]
