# Generated by Django 4.1.4 on 2022-12-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0007_alter_videosdetails_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosdetails',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
