# Generated by Django 4.1.4 on 2022-12-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0010_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
