# Generated by Django 4.1.4 on 2022-12-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0013_remove_userdetails_userid_userdetails_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userId',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
