# Generated by Django 4.1.4 on 2022-12-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0018_remove_userdetails_userid_userdetails_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
