# Generated by Django 4.1.4 on 2023-01-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0023_remove_videosdetails_id_videosdetails_videosid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosdetails',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
