# Generated by Django 4.1.4 on 2023-01-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0025_alter_videosdetails_genre_alter_videosdetails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosdetails',
            name='video',
            field=models.FileField(null=True, upload_to='videos/%y', verbose_name='Video'),
        ),
    ]
