# Generated by Django 4.1.4 on 2023-01-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0026_alter_videosdetails_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosdetails',
            name='videosId',
        ),
        migrations.AddField(
            model_name='videosdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videosdetails',
            name='type',
            field=models.CharField(choices=[('Music Videos', 'Musicvideos'), ('Web Series', 'Webseries'), ('Movies', 'Movies'), ('Trailers', 'Trailers'), ('Kids', 'Kids'), ('Devotional', 'Devotional')], default='Music Videos', max_length=12),
        ),
    ]
