# Generated by Django 4.1.4 on 2023-01-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0027_remove_videosdetails_videosid_videosdetails_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='videosdetails',
            name='videosId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
