# Generated by Django 4.1.4 on 2022-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0008_alter_videosdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosdetails',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='videosdetails',
            name='thumbnailImage',
            field=models.ImageField(upload_to='thumbnailImage/'),
        ),
        migrations.AlterField(
            model_name='videosdetails',
            name='titleImage',
            field=models.ImageField(upload_to='titleImage/'),
        ),
        migrations.AlterField(
            model_name='videosdetails',
            name='trailer',
            field=models.FileField(null=True, upload_to='tailers/', verbose_name='Trailer'),
        ),
    ]
