# Generated by Django 4.1.4 on 2022-12-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0019_remove_userdetails_id_userdetails_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
