# Generated by Django 4.1.4 on 2023-01-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0021_remove_videosdetails_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosdetails',
            name='VIDEOS',
        ),
        migrations.AddField(
            model_name='videosdetails',
            name='type',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
